# Generated by Django 5.0 on 2024-01-04 19:01

import django.db.models.deletion
import servers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=servers.models.category_icon_file_path,
                verbose_name="Category Icon",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Channel Owner",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Server Description"
            ),
        ),
    ]
